import { getOrgRepos, getRepoParticipation } from '@/shared/api/github'
import { Card } from '@/shared/ui/Card'
import { ActivitySparkline } from './ActivitySparkline'

export async function ActivityCard({ org }: { org: string }) {
  const repos = await getOrgRepos(org)
  const flagship = repos[0]
  const participation = flagship ? await getRepoParticipation(flagship.full_name) : null

  if (!flagship || !participation) {
    return (
      <Card title="Commit activity">
        <p className="py-20 text-center text-sm text-zinc-500">
          Commit stats are being generated by GitHub. Refresh in a moment.
        </p>
      </Card>
    )
  }

  const data = participation.all.map((commits, index) => ({
    week: `W${index + 1}`,
    commits,
  }))

  return (
    <Card title={`Commit activity · ${flagship.name} · last 52 weeks`}>
      <ActivitySparkline data={data} />
    </Card>
  )
}
